language: go

go:
  - - "1.11"

script:
  - ./build.sh

deploy:
  provider: releases
  api_key:
    secure: $GITHUB_API_KEY
  file_glob: true
  file:
    - build/*.tar.xz*
  skip_cleanup: true
  on:
    tags: true
